site_name: ""

docs_dir: pages

nav:
  - 主页: https://robin.ar
  - 索引: index.md
  - 2025年1月31日 方 Robin: 00.md
  - 2025年1月31日 方 HuiZhen: 01.md
  - 2025年2月2日 方 Robin: 02.md
  - 2025年2月2日 方 HuiZhen: 03.md
  - 2025年2月4日 方 HuiZhen: 04.md
  - 2025年2月6日 方 Robin: 05.md
  - 2025年3月16日 方 Robin: 06.md
  - 2025年3月17日 方 HuiZhen: 07.md
  - 2025年3月19日 方 Robin: 08.md

theme:
  name: material
  font:
    text: "Merriweather"
    code: "Noto Sans Traditional Chinese"
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.autohide
    - content.code.annotate
    - content.tooltips
    - header.autohide

extra_css:
  - styles/letter.css

extra_javascript:
  - styles/letter.js

extra:
  generator: false

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes